[project]
name = "hawkbit-server"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn"
]
requires-python = ">=3.8"

[tool.hatch.build.targets.wheel]
packages = ["."]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"